"""agregar fecha_gestion a donaciones fisicas y monetarias

Revision ID: 0b411d822193
Revises: 359711da02cd
Create Date: 2026-06-22 08:34:01.875721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b411d822193'
down_revision = '359711da02cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones_fisicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_gestion', sa.TIMESTAMP(), nullable=True))

    with op.batch_alter_table('donaciones_monetarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_gestion', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones_monetarias', schema=None) as batch_op:
        batch_op.drop_column('fecha_gestion')

    with op.batch_alter_table('donaciones_fisicas', schema=None) as batch_op:
        batch_op.drop_column('fecha_gestion')

    # ### end Alembic commands ###
