"""agregar campos de contacto a fundacion

Revision ID: 1373585e2102
Revises: 
Create Date: 2026-06-14 17:01:13.216927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1373585e2102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donaciones_fisicas')
    op.drop_table('transacciones')
    op.drop_table('tickets_soporte')
    with op.batch_alter_table('donaciones', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('necesidad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('monto',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('token_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('email_contacto')
        batch_op.drop_column('tipo_ayuda')
        batch_op.drop_column('nombre_contacto')
        batch_op.drop_column('fundacion_destino')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('donante_id')

    with op.batch_alter_table('fundaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('esta_validada')

    with op.batch_alter_table('necesidades', schema=None) as batch_op:
        batch_op.alter_column('fundacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cantidad_requerida')
        batch_op.drop_column('categoria')
        batch_op.drop_column('detalles_json')
        batch_op.drop_column('cantidad_comprometida')
        batch_op.drop_column('fecha_limite')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('tipo_persona')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_persona', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('necesidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_limite', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cantidad_comprometida', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('detalles_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cantidad_requerida', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.alter_column('fundacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fundaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esta_validada', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('email')
        batch_op.drop_column('telefono')

    with op.batch_alter_table('donaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donante_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fundacion_destino', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_ayuda', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('token_uuid',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('monto',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('necesidad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('tickets_soporte',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email_contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('categoria_fallo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('titulo_falla', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion_falla', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'abierto'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_soporte_pkey')),
    sa.UniqueConstraint('token_uuid', name=op.f('tickets_soporte_token_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transacciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('donacion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('transaccion_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ultimos_cuatro', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['donacion_id'], ['donaciones.id'], name=op.f('transacciones_donacion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transacciones_pkey')),
    sa.UniqueConstraint('transaccion_token', name=op.f('transacciones_transaccion_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('donaciones_fisicas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('necesidad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('donante_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fundacion_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('articulo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cantidad_comprometida', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['donante_id'], ['usuarios.id'], name=op.f('donaciones_fisicas_donante_id_fkey')),
    sa.ForeignKeyConstraint(['fundacion_id'], ['fundaciones.id'], name=op.f('donaciones_fisicas_fundacion_id_fkey')),
    sa.ForeignKeyConstraint(['necesidad_id'], ['necesidades.id'], name=op.f('donaciones_fisicas_necesidad_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('donaciones_fisicas_pkey'))
    )
    # ### end Alembic commands ###
