"""agregar_estado_a_donacion_monetaria

Revision ID: 359711da02cd
Revises: 502413dd0576
Create Date: 2026-06-20 16:33:24.000526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359711da02cd'
down_revision = '502413dd0576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones_monetarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones_monetarias', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
