"""agregar estado a donaciones_monetarias

Revision ID: 502413dd0576
Revises: 58e298b83a8b
Create Date: 2026-06-20 08:16:20.448015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '502413dd0576'
down_revision = '58e298b83a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('necesidad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('token_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['necesidad_id'], ['necesidades.id'], name=op.f('donaciones_necesidad_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('donaciones_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('donaciones_pkey')),
    sa.UniqueConstraint('token_uuid', name=op.f('donaciones_token_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
