"""agregar campo nit a fundaciones

Revision ID: 58e298b83a8b
Revises: 9999536e9b6a
Create Date: 2026-06-17 13:15:25.822176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e298b83a8b'
down_revision = '9999536e9b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundaciones', schema=None) as batch_op:
        batch_op.drop_column('nit')

    # ### end Alembic commands ###
