"""Sincronizacion de modelos

Revision ID: 9999536e9b6a
Revises: d45d6decff29
Create Date: 2026-06-17 11:25:23.769232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9999536e9b6a'
down_revision = 'd45d6decff29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones_fisicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donaciones_fisicas', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
