"""empty message

Revision ID: d45d6decff29
Revises: 1373585e2102
Create Date: 2026-06-15 20:02:41.655463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd45d6decff29'
down_revision = '1373585e2102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_column('ip')
        batch_op.drop_column('recurso_afectado')
        batch_op.drop_column('motivo')

    with op.batch_alter_table('donaciones_monetarias', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)

    with op.batch_alter_table('fundaciones', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fundaciones_nit_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fundaciones_admin_validador_id_fkey'), type_='foreignkey')
        batch_op.drop_column('nit')
        batch_op.drop_column('es_verificado')
        batch_op.drop_column('telefono')
        batch_op.drop_column('created_at')
        batch_op.drop_column('nombre_persona_cargo')
        batch_op.drop_column('admin_validador_id')
        batch_op.drop_column('fecha_aprobacion')
        batch_op.drop_column('email')

    with op.batch_alter_table('necesidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_comprometida', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
        batch_op.drop_column('monto_objetivo')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('estado_validacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_validacion', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('necesidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_objetivo', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('categoria')
        batch_op.drop_column('cantidad_comprometida')

    with op.batch_alter_table('fundaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_aprobacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_validador_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_persona_cargo', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('es_verificado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fundaciones_admin_validador_id_fkey'), 'usuarios', ['admin_validador_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('fundaciones_nit_key'), ['nit'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('donaciones_monetarias', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recurso_afectado', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
